"""Database layer: Postgres (Supabase) in the cloud, SQLite on a laptop.

  DATABASE_URL=postgresql://...   -> Postgres through a small connection pool
  (not set)                       -> SQLite file proctor.db next to this file

The SQL in app.py is written once for both: "?" placeholders are converted
for Postgres, and GREATEST/LEAST below cover the one function that differs.

Secrets (exam PINs, student upload tokens, admin session tokens) are stored
only as keyed hashes; admin passwords as scrypt.

On Supabase, row-level security is switched on for every table with no
policies, so Supabase's public REST API (anon key) cannot read or write them.
This server connects as the table owner, which is not affected.
"""
import atexit
import hashlib
import hmac
import os
import secrets
import sqlite3
import time
from contextlib import contextmanager
from pathlib import Path

BASE = Path(__file__).resolve().parent
DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
PG = DATABASE_URL.startswith(("postgres://", "postgresql://"))
SQLITE_PATH = Path(os.environ.get("PROCTOR_DB", BASE / "proctor.db"))

GREATEST, LEAST = ("GREATEST", "LEAST") if PG else ("max", "min")
_ID = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if PG else "INTEGER PRIMARY KEY AUTOINCREMENT"
TABLES = ("admins", "sessions", "exams", "participants", "presence", "events", "flags")

# Timestamps are Unix seconds in DOUBLE PRECISION (Postgres REAL is only 4 bytes: too coarse).
SCHEMA = f"""
CREATE TABLE IF NOT EXISTS admins(
    username TEXT PRIMARY KEY,
    pw_hash TEXT NOT NULL,
    created_ts DOUBLE PRECISION NOT NULL
);
CREATE TABLE IF NOT EXISTS sessions(
    token_hash TEXT PRIMARY KEY,
    username TEXT NOT NULL,
    expires_ts DOUBLE PRECISION NOT NULL
);
CREATE TABLE IF NOT EXISTS exams(
    code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    start_ts DOUBLE PRECISION NOT NULL,
    end_ts DOUBLE PRECISION NOT NULL,
    pin_hash TEXT NOT NULL,
    allowed_sites TEXT NOT NULL DEFAULT '[]',
    grace_s INTEGER NOT NULL DEFAULT 3,
    flag_outside INTEGER NOT NULL DEFAULT 1,
    roster TEXT NOT NULL DEFAULT '[]',
    created_by TEXT NOT NULL DEFAULT '',
    created_ts DOUBLE PRECISION NOT NULL
);
CREATE TABLE IF NOT EXISTS participants(
    exam_code TEXT NOT NULL,
    roll_no TEXT NOT NULL,
    name TEXT NOT NULL DEFAULT '',
    device_id TEXT NOT NULL,
    joined_ts DOUBLE PRECISION NOT NULL,
    token_hash TEXT NOT NULL,
    uninstall_key TEXT NOT NULL,
    PRIMARY KEY (exam_code, roll_no)
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_part_token ON participants(token_hash);
CREATE INDEX IF NOT EXISTS ix_part_ukey ON participants(uninstall_key);
CREATE TABLE IF NOT EXISTS presence(
    exam_code TEXT NOT NULL,
    roll_no TEXT NOT NULL,
    last_seen DOUBLE PRECISION NOT NULL,
    kind TEXT NOT NULL DEFAULT '',
    domain TEXT NOT NULL DEFAULT '',
    path TEXT NOT NULL DEFAULT '',
    title TEXT NOT NULL DEFAULT '',
    since DOUBLE PRECISION NOT NULL DEFAULT 0,
    allowed INTEGER NOT NULL DEFAULT 1,
    bad_tabs TEXT NOT NULL DEFAULT '[]',
    PRIMARY KEY (exam_code, roll_no)
);
CREATE TABLE IF NOT EXISTS events(
    id {_ID},
    exam_code TEXT NOT NULL,
    roll_no TEXT NOT NULL,
    kind TEXT NOT NULL,
    domain TEXT NOT NULL,
    path TEXT NOT NULL DEFAULT '',
    title TEXT NOT NULL DEFAULT '',
    start_ts DOUBLE PRECISION NOT NULL,
    end_ts DOUBLE PRECISION NOT NULL,
    allowed INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_events ON events(exam_code, roll_no, start_ts);
CREATE TABLE IF NOT EXISTS flags(
    id {_ID},
    exam_code TEXT NOT NULL,
    roll_no TEXT NOT NULL,
    rule TEXT NOT NULL,
    level TEXT NOT NULL,
    domain TEXT NOT NULL DEFAULT '',
    path TEXT NOT NULL DEFAULT '',
    title TEXT NOT NULL DEFAULT '',
    detail TEXT NOT NULL DEFAULT '',
    seg_start DOUBLE PRECISION NOT NULL,
    duration_s DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_ts DOUBLE PRECISION NOT NULL,
    updated_ts DOUBLE PRECISION NOT NULL,
    status TEXT NOT NULL DEFAULT 'open',
    note TEXT NOT NULL DEFAULT '',
    reviewer TEXT NOT NULL DEFAULT ''
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_flags ON flags(exam_code, roll_no, rule, domain, seg_start);
CREATE INDEX IF NOT EXISTS ix_flags_upd ON flags(exam_code, updated_ts);
"""


# ---------------------------------------------------------------- Postgres
class Row(tuple):
    """Row readable by position, by column name, and with dict(row), like sqlite3.Row."""

    def __new__(cls, values, index):
        r = super().__new__(cls, values)
        r._index = index
        return r

    def __getitem__(self, k):
        return tuple.__getitem__(self, self._index[k] if isinstance(k, str) else k)

    def keys(self):
        return self._index.keys()


def _row_factory(cursor):
    index = {d.name: i for i, d in enumerate(cursor.description or [])}
    return lambda values: Row(values, index)


class _PgConn:
    """Gives a psycopg connection the sqlite3 interface app.py uses."""

    def __init__(self, c):
        self.c = c

    def execute(self, sql, params=()):
        return self.c.execute(sql.replace("?", "%s"), params)

    def executemany(self, sql, rows):
        if rows:
            with self.c.cursor() as cur:
                cur.executemany(sql.replace("?", "%s"), rows)


_pool = None


def _open_pool():
    global _pool
    if _pool is None:
        from psycopg_pool import ConnectionPool
        _pool = ConnectionPool(
            DATABASE_URL, min_size=1, max_size=int(os.environ.get("DB_POOL_SIZE", "10")), timeout=20,
            # prepare_threshold=None: works through Supabase's transaction pooler (port 6543) too.
            kwargs={"prepare_threshold": None, "connect_timeout": 10},
            configure=lambda c: setattr(c, "row_factory", _row_factory),
            check=ConnectionPool.check_connection, open=True)
        atexit.register(close)
    return _pool


# ---------------------------------------------------------------- common API
def init():
    if PG:
        with _open_pool().connection() as c:
            for stmt in filter(str.strip, SCHEMA.split(";")):
                c.execute(stmt)
            for t in TABLES:
                c.execute(f"ALTER TABLE {t} ENABLE ROW LEVEL SECURITY")
    else:
        c = sqlite3.connect(SQLITE_PATH)
        c.execute("PRAGMA journal_mode=WAL")
        c.executescript(SCHEMA)
        c.close()


@contextmanager
def conn():
    if PG:
        with _open_pool().connection() as c:   # commits on success, rolls back on error
            yield _PgConn(c)
        return
    c = sqlite3.connect(SQLITE_PATH, timeout=15)
    c.row_factory = sqlite3.Row
    c.execute("PRAGMA synchronous=NORMAL")
    try:
        yield c
        c.commit()
    except BaseException:
        c.rollback()
        raise
    finally:
        c.close()


def close():
    global _pool
    if _pool is not None:
        _pool.close()
        _pool = None


def _secret() -> bytes:
    s = os.environ.get("PROCTOR_SECRET")
    if not s or len(s) < 16:
        raise RuntimeError("Set PROCTOR_SECRET to a long random string (see README).")
    return s.encode()


def secret_hash(*parts: str) -> str:
    """Keyed hash for PINs and tokens, so the database never holds them in plain text."""
    return hmac.new(_secret(), "|".join(parts).encode(), hashlib.sha256).hexdigest()


def hash_password(pw: str) -> str:
    salt = secrets.token_bytes(16)
    h = hashlib.scrypt(pw.encode(), salt=salt, n=2**14, r=8, p=1, dklen=32)
    return f"scrypt${salt.hex()}${h.hex()}"


def check_password(pw: str, stored: str) -> bool:
    try:
        _, salt, h = stored.split("$")
    except ValueError:
        return False
    got = hashlib.scrypt(pw.encode(), salt=bytes.fromhex(salt), n=2**14, r=8, p=1, dklen=32)
    return hmac.compare_digest(got.hex(), h)


def now() -> float:
    return time.time()
